version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    build: .
    ports:
      - "5044:5044"   # HTTP portunu map ediyor
      - "7266:7266"   # HTTPS portunu map ediyor
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=your_database_name;User=your_user;Password=your_password;"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
