version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ProductManagementDb
      MYSQL_USER: burak
      MYSQL_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    build: .
    ports:
      - "8080:8080"   # HTTP portunu map ediyor
      - "7266:7266"   # HTTPS portunu map ediyor
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Database=ProductManagementDb;User=root;Password=123456"
      

    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
